# Generated by Django 3.2 on 2022-09-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='totalrating',
            field=models.IntegerField(default=0),
        ),
    ]
