# Generated by Django 3.2 on 2022-09-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0002_video_totalrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='avgrating',
            field=models.FloatField(default=0),
        ),
    ]
