# Generated by Django 3.2 on 2022-09-02 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0002_streamingplatform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamingplatform',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='video',
            name='watchlist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='ratingapp.streamingplatform'),
            preserve_default=False,
        ),
    ]
