# Generated by Django 3.2 on 2022-09-02 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='ratingfield',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ratingfield', to='ratingapp.video'),
            preserve_default=False,
        ),
    ]
