# Generated by Django 3.2 on 2022-09-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0005_rating_ratingfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='ratingfield',
            new_name='assocvideo',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='watchlist',
            new_name='streamingplatform',
        ),
    ]
